
function select1(){
document.getElementById("one").setAttribute('visible', false);
document.getElementById("demo").setAttribute('visible', false);                 
document.getElementById("seven").setAttribute('visible', true);
document.getElementById("eight").setAttribute('visible', true);
document.getElementById("two").setAttribute('visible', false);
document.getElementById("demo2").setAttribute('visible', false);
document.getElementById("nine").setAttribute('visible', false);
document.getElementById("ten").setAttribute('visible', false);
document.getElementById("three").setAttribute('visible', false);
document.getElementById("demo3").setAttribute('visible', false);
document.getElementById("eleven").setAttribute('visible', false);
document.getElementById("twelve").setAttribute('visible', false);
document.getElementById("four").setAttribute('visible', false);
document.getElementById("demo4").setAttribute('visible', false);
document.getElementById("thirteen").setAttribute('visible', false);
document.getElementById("fourteen").setAttribute('visible', false);
document.getElementById("five").setAttribute('visible', false);
document.getElementById("demo5").setAttribute('visible', false);
document.getElementById("fifteen").setAttribute('visible', false);
document.getElementById("sixteen").setAttribute('visible', false);
document.getElementById("six").setAttribute('visible', false);
document.getElementById("demo6").setAttribute('visible', false);
document.getElementById("seventeen").setAttribute('visible', false);
document.getElementById("eightteen").setAttribute('visible', false);
}

function select2(){
document.getElementById("one").setAttribute('visible', false);
document.getElementById("demo").setAttribute('visible', false);                 
document.getElementById("seven").setAttribute('visible', false);
document.getElementById("eight").setAttribute('visible', false);
document.getElementById("two").setAttribute('visible', false);
document.getElementById("demo2").setAttribute('visible', false);
document.getElementById("nine").setAttribute('visible', true);
document.getElementById("ten").setAttribute('visible', true);
document.getElementById("three").setAttribute('visible', false);
document.getElementById("demo3").setAttribute('visible', false);
document.getElementById("eleven").setAttribute('visible', false);
document.getElementById("twelve").setAttribute('visible', false);
document.getElementById("four").setAttribute('visible', false);
document.getElementById("demo4").setAttribute('visible', false);
document.getElementById("thirteen").setAttribute('visible', false);
document.getElementById("fourteen").setAttribute('visible', false);
document.getElementById("five").setAttribute('visible', false);
document.getElementById("demo5").setAttribute('visible', false);
document.getElementById("fifteen").setAttribute('visible', false);
document.getElementById("sixteen").setAttribute('visible', false);
document.getElementById("six").setAttribute('visible', false);
document.getElementById("demo6").setAttribute('visible', false);
document.getElementById("seventeen").setAttribute('visible', false);
document.getElementById("eightteen").setAttribute('visible', false);
}

function select3(){
document.getElementById("one").setAttribute('visible', false);
document.getElementById("demo").setAttribute('visible', false);                 
document.getElementById("seven").setAttribute('visible', false);
document.getElementById("eight").setAttribute('visible', false);
document.getElementById("two").setAttribute('visible', false);
document.getElementById("demo2").setAttribute('visible', false);
document.getElementById("nine").setAttribute('visible', false);
document.getElementById("ten").setAttribute('visible', false);
document.getElementById("three").setAttribute('visible', false);
document.getElementById("demo3").setAttribute('visible', false);
document.getElementById("eleven").setAttribute('visible', true);
document.getElementById("twelve").setAttribute('visible', true);
document.getElementById("four").setAttribute('visible', false);
document.getElementById("demo4").setAttribute('visible', false);
document.getElementById("thirteen").setAttribute('visible', false);
document.getElementById("fourteen").setAttribute('visible', false);
document.getElementById("five").setAttribute('visible', false);
document.getElementById("demo5").setAttribute('visible', false);
document.getElementById("fifteen").setAttribute('visible', false);
document.getElementById("sixteen").setAttribute('visible', false);
document.getElementById("six").setAttribute('visible', false);
document.getElementById("demo6").setAttribute('visible', false);
document.getElementById("seventeen").setAttribute('visible', false);
document.getElementById("eightteen").setAttribute('visible', false);
}

function select4(){
document.getElementById("one").setAttribute('visible', false);
document.getElementById("demo").setAttribute('visible', false);                 
document.getElementById("seven").setAttribute('visible', false);
document.getElementById("eight").setAttribute('visible', false);
document.getElementById("two").setAttribute('visible', false);
document.getElementById("demo2").setAttribute('visible', false);
document.getElementById("nine").setAttribute('visible', false);
document.getElementById("ten").setAttribute('visible', false);
document.getElementById("three").setAttribute('visible', false);
document.getElementById("demo3").setAttribute('visible', false);
document.getElementById("eleven").setAttribute('visible', false);
document.getElementById("twelve").setAttribute('visible', false);
document.getElementById("four").setAttribute('visible', false);
document.getElementById("demo4").setAttribute('visible', false);
document.getElementById("thirteen").setAttribute('visible', true);
document.getElementById("fourteen").setAttribute('visible', true);
document.getElementById("five").setAttribute('visible', false);
document.getElementById("demo5").setAttribute('visible', false);
document.getElementById("fifteen").setAttribute('visible', false);
document.getElementById("sixteen").setAttribute('visible', false);
document.getElementById("six").setAttribute('visible', false);
document.getElementById("demo6").setAttribute('visible', false);
document.getElementById("seventeen").setAttribute('visible', false);
document.getElementById("eightteen").setAttribute('visible', false);
}

function select5(){
document.getElementById("one").setAttribute('visible', false);
document.getElementById("demo").setAttribute('visible', false);                 
document.getElementById("seven").setAttribute('visible', false);
document.getElementById("eight").setAttribute('visible', false);
document.getElementById("two").setAttribute('visible', false);
document.getElementById("demo2").setAttribute('visible', false);
document.getElementById("nine").setAttribute('visible', false);
document.getElementById("ten").setAttribute('visible', false);
document.getElementById("three").setAttribute('visible', false);
document.getElementById("demo3").setAttribute('visible', false);
document.getElementById("eleven").setAttribute('visible', false);
document.getElementById("twelve").setAttribute('visible', false);
document.getElementById("four").setAttribute('visible', false);
document.getElementById("demo4").setAttribute('visible', false);
document.getElementById("thirteen").setAttribute('visible', false);
document.getElementById("fourteen").setAttribute('visible', false);
document.getElementById("five").setAttribute('visible', false);
document.getElementById("demo5").setAttribute('visible', false);
document.getElementById("fifteen").setAttribute('visible', true);
document.getElementById("sixteen").setAttribute('visible', true);
document.getElementById("six").setAttribute('visible', false);
document.getElementById("demo6").setAttribute('visible', false);
document.getElementById("seventeen").setAttribute('visible', false);
document.getElementById("eightteen").setAttribute('visible', false);
}

function select6(){
document.getElementById("one").setAttribute('visible', false);
document.getElementById("demo").setAttribute('visible', false);                 
document.getElementById("seven").setAttribute('visible', false);
document.getElementById("eight").setAttribute('visible', false);
document.getElementById("two").setAttribute('visible', false);
document.getElementById("demo2").setAttribute('visible', false);
document.getElementById("nine").setAttribute('visible', false);
document.getElementById("ten").setAttribute('visible', false);
document.getElementById("three").setAttribute('visible', false);
document.getElementById("demo3").setAttribute('visible', false);
document.getElementById("eleven").setAttribute('visible', false);
document.getElementById("twelve").setAttribute('visible', false);
document.getElementById("four").setAttribute('visible', false);
document.getElementById("demo4").setAttribute('visible', false);
document.getElementById("thirteen").setAttribute('visible', false);
document.getElementById("fourteen").setAttribute('visible', false);
document.getElementById("five").setAttribute('visible', false);
document.getElementById("demo5").setAttribute('visible', false);
document.getElementById("fifteen").setAttribute('visible', false);
document.getElementById("sixteen").setAttribute('visible', false);
document.getElementById("six").setAttribute('visible', false);
document.getElementById("demo6").setAttribute('visible', false);
document.getElementById("seventeen").setAttribute('visible', true);
document.getElementById("eightteen").setAttribute('visible', true);
}

